new: className in subclass constructor
parse-community/Parse-SDK-JS pull request #1315
Opened 2021-03-08 13:56 UTC by dblythy

Hi,

Let's say you want to create a global function `getName` on all your Parse.Objects. Let's say you have 4 different classes. Here's how you'd have to do that now:

```javascript
class ClassOne extends ParseObject {
  constructor() {
    super('ClassOne');
  }
  getDetails() {
    return `${this.get('title')} ${this.get('description')}`;
  }
}
class ClassTwo extends ParseObject {
  constructor() {
    super('ClassTwo');
  }
  getDetails() {
    return `${this.get('title')} ${this.get('description')}`;
  }
}
class ClassThree extends ParseObject {
  constructor() {
    super('ClassThree');
  }
  getDetails() {
    return `${this.get('title')} ${this.get('description')}`;
  }
}
ParseObject.registerSubclass('ClassOne', ClassOne);
ParseObject.registerSubclass('ClassTwo', ClassTwo);
ParseObject.registerSubclass('ClassThree', ClassThree);
```

Now, obviously this doesn't apply to all use cases, but this allows a `registeredSubclass` to have multiple class names, meaning that you can create one overhead class for multiple Parse classes.

```javascript
class ParseHelper extends ParseObject {
  constructor(className) {
    super(className);
  }
  getDetails() {
    return `${this.get('title')} ${this.get('description')}`;
  }
}
const classNames = ['ClassOne', 'ClassTwo', 'ClassThree'];
for (const className of classNames) {
  Parse.Object.registerSubclass(className, ParseHelper);
}
```

2021-03-08 16:47 UTC, dplewis commented
Can you write a failing test? I kinda know what you are trying to do.

2021-03-08 17:01 UTC, dblythy commented
> Can you write a failing test? I kinda know what you are trying to do.

Yes, the main problem is that subclassing doesn't work without `super(ClassName)`, and ClassName has to be, well, the class name.

```
it('can use on ParseObject subclass for multiple Parse.Object class names', () => {
  class MyParseObjects extends ParseObject {
    constructor() {
      super();
    }
  
    doSomething() {
      return 5;
    }
  
    static readOnlyAttributes() {
      return ['readonly', 'static', 'frozen'];
    }
  }
  ParseObject.registerSubclass('TestObject', MyParseObjects);
  ParseObject.registerSubclass('TestObject1', MyParseObjects);
  ParseObject.registerSubclass('TestObject2', MyParseObjects);
  const obj = new MyParseObjects('TestObject');
  expect(obj.className).toBe('TestObject');
  const obj1 = new MyParseObjects('TestObject1');
  expect(obj1.className).toBe('TestObject1');
  const obj2 = new MyParseObjects('TestObject2');
  expect(obj2.className).toBe('TestObject2');
});
```

2021-03-08 17:39 UTC, dplewis requested changes
Just a quick nit. Nice catch!

2021-03-08 17:39 UTC, dplewis commented on src/__tests__/ParseObject-test.js
> +  it('can use on ParseObject subclass for multiple Parse.Object class names', () => {
Can you add spaces between tests.

2021-03-08 17:39 UTC, dplewis commented on integration/test/ParseSubclassTest.js
> +  it('registerSubclass with unknown className', async () => {
Can you add spaces between tests.

2021-03-09 02:03 UTC, dplewis approved these changes

2021-03-09 02:03 UTC, merged

2021-03-09 02:27 UTC, dblythy commented
Thanks @dplewis! Will be very helpful for me on Vue projects.

Note that this will have implications for #924

2021-03-09 02:28 UTC, dplewis commented
I’m surprise nobody caught this. Should look into #924