chore: failing unit test for #1510
parse-community/Parse-SDK-JS pull request #1517
Opened 2022-07-27 19:05 UTC by justinlettau

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

Related issue: #1510

### Approach

Adding a failing unit test for reproducing base64 regex issue.

### TODOs before merging

- [x] Add tests

2022-07-28 14:34 UTC, mtrezza requested changes

2022-07-28 14:34 UTC, mtrezza commented on src/ParseFile.js
> +  '([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=)|([0-9a-zA-Z+/]{4}))',
```suggestion
  '([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/][AQgw]==)|([0-9a-zA-Z+/]{2}[AEIMQUYcgkosw048]=)|([0-9a-zA-Z+/]{4}))',
```

2022-07-28 16:38 UTC, mtrezza approved these changes
Looks good!

2022-07-28 16:39 UTC, mtrezza commented
off-topic: @dblythy it's interesting that the CI passes here

2022-07-28 16:41 UTC, merged

2022-07-28 16:57 UTC, parseplatformorg commented
🎉 This change has been released in version [3.4.4-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.4-alpha.1)

2022-10-25 22:21 UTC, parseplatformorg commented
🎉 This change has been released in version [3.5.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0-beta.1)

2022-11-01 21:44 UTC, parseplatformorg commented
🎉 This change has been released in version [3.5.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0)