fix: add context to signup
parse-community/Parse-SDK-JS pull request #1527
Opened 2022-08-15 03:46 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue Description

`context` object isn't passed to `signup`.

Related issue: #1526

### Approach

Pass context object

### TODOs before merging

- [x] Add tests

2022-08-15 10:07 UTC, mtrezza requested changes

2022-08-15 10:07 UTC, mtrezza commented on src/ParseUser.js
> +    if (options.hasOwnProperty('context') && typeof options.context === 'object') {
`typeof options.context === 'object'` would pass for many types, even `new String()`.

A more specific test would be `Object.prototype.toString.call(context) === '[object Object]'`

2022-08-16 09:47 UTC, mtrezza approved these changes
Looks good!

2022-08-16 09:47 UTC, merged

2022-08-16 10:03 UTC, parseplatformorg commented
🎉 This change has been released in version [3.4.4-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.4.4-alpha.2)

2022-10-25 22:21 UTC, parseplatformorg commented
🎉 This change has been released in version [3.5.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0-beta.1)

2022-11-01 21:44 UTC, parseplatformorg commented
🎉 This change has been released in version [3.5.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0)