Fix type doc & def for containedIn and notContainedIn
parse-community/Parse-SDK-JS pull request #1784
Opened 2023-02-20 16:21 UTC by richardgroves

Fixes https://github.com/parse-community/Parse-SDK-JS/issues/1783

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-JS/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

## Issue
[]

Closes: #1783 

## Approach

Documentation and method parameter type updated for `Parse.Query.containedIn` and `Parse.Query.notContainedIn`

## Tasks

- [ ] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

2023-02-20 16:25 UTC, richardgroves commented
> ### Thanks for opening this pull request!
> * ❌ Please edit your post and use the provided template when creating a new pull request. This helps everyone to understand your post better and asks for essential information to quicker review the pull request.

I'm not sure which bit of the template I didn't use, AFAICS I filled in each section.

2023-02-20 16:26 UTC, mtrezza commented
All good, I remove the "Fixes https://github.com/parse-community/Parse-SDK-JS/issues/1783" at the top, that's what the "Closes:" is for.

2023-02-20 16:35 UTC, mtrezza commented on src/ParseQuery.js
> +   * @param {array} value The values that will match.
```suggestion
   * @param {Array<String>} value The values that will match.
```

2023-02-20 16:45 UTC, mtrezza requested changes
It may be more correct to specify the exact types that can be passed, unless really *any* type can be passed, including objects, array, etc.

`Array<null|undefined|String|Number|Boolean>`

2023-02-20 16:45 UTC, mtrezza commented on src/ParseQuery.js
> +   * @param {array} value The values that will match.
```suggestion
   * @param {Array<*>} value The values that will match.
```

2023-02-20 16:45 UTC, mtrezza commented on src/ParseQuery.js
> +   * @param {array} value The values that will not match.
```suggestion
   * @param {Array<*>} value The values that will not match.
```

2023-02-20 17:11 UTC, richardgroves commented
> The tests fail because in JSDos it's `Array`. It may be more correct to specify the exact types that can be passed, unless really _any_ type can be passed, including objects, array, etc.
> 
> `Array<null|undefined|String|Number|Boolean>` is just a guess

I'm not 100% sure what types can be in the array, and whether an array of items has to be of a single type or can have mixed contents. Would specifying the type list limit it to an array of homogenous types?

I know I have arrays of objects (or object pointers internally) so 'object' would have to be in the list of allowed types.

2023-02-20 17:33 UTC, mtrezza commented
> Would specifying the type list limit it to an array of homogenous types?

Yes. So let's go with `Array<*>` I guess.

2023-02-21 00:56 UTC, mtrezza approved these changes
Looks good!

2023-02-21 00:57 UTC, merged

2023-03-01 15:20 UTC, parseplatformorg commented
🎉 This change has been released in version [4.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-beta.1)

2023-03-01 15:48 UTC, parseplatformorg commented
🎉 This change has been released in version [4.1.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-alpha.1)

2023-05-01 22:11 UTC, parseplatformorg commented
🎉 This change has been released in version [4.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0)