feat: EventuallyQueue changeable through CoreManager
parse-community/Parse-SDK-JS pull request #2106
Opened 2024-04-13 15:16 UTC by mortenmo

EventuallyQueue behavior isn't always what I need. Was hoping to have a way to replace the default to change the behavior. Using CoreManager felt like the obvious way.

## Issue

EventuallyQueue gives you no control over what happens if there are conflicts. For example,  another client has changed the object, it just looks at updatedAt time and drops the local changes. Fine as a general rule, but sometimes I need some control over that in an often offline environment.

## Approach

There were only 3 places that called EventuallyQueue directly. Just changed those to use `CoreManager.getEventuallyQueue()` following the patterns of most other things going through CoreManager.

## Tasks

- [X] Fix tests if needed
- [] Documentation??

2024-04-13 15:29 UTC, dplewis commented
Looks good! I think you may have fixed a circular dependency as well.

2024-04-13 22:00 UTC, dplewis requested changes

2024-04-13 22:00 UTC, dplewis commented on src/Parse.ts
> +        CoreManager.getEventuallyQueue().poll(ms);
@mortenmo `Parse.EventuallyQueue` will have to get retrieved from the CoreManager now instead of the `EventuallyQueue` import.

```
/**
   * @member {EventuallyQueue} Parse.EventuallyQueue
   * @static
   */
  set EventuallyQueue(queue: EventuallyQueue) {
    CoreManager.setEventuallyQueue(queue);
  },
  get EventuallyQueue() {
    return CoreManager.getEventuallyQueue();
  },

2024-04-14 01:36 UTC, mortenmo commented on src/Parse.ts
> +        CoreManager.getEventuallyQueue().poll(ms);
oh yeah, good catch, forgot about accessing it that way.

2024-04-14 01:38 UTC, dplewis commented on src/Parse.ts
> +        CoreManager.getEventuallyQueue().poll(ms);
I just did the same thing for Parse.LiveQuery if you want to check it out https://github.com/parse-community/Parse-SDK-JS/pull/2100/commits/2d838b54b4c1e13668d6c85f3e88bf3810ea1002

2024-04-14 01:42 UTC, mortenmo commented on src/Parse.ts
> +        CoreManager.getEventuallyQueue().poll(ms);
committed your suggestion..

 I noticed this code in `_initialize`: 
```
    Parse.LiveQuery = new LiveQuery();
    CoreManager.setIfNeeded('LiveQuery', Parse.LiveQuery);
```

Has some of the same issue. If you did set your own `LiveQuery`, `Parse.LiveQuery` wouldn't reflect the same implementation. Never tried to do that myself or know if there is any bad sideeffects of it.

2024-04-14 01:43 UTC, dplewis commented on src/Parse.ts
> +        CoreManager.getEventuallyQueue().poll(ms);
Look at my last comment

2024-04-14 01:46 UTC, mortenmo commented on src/Parse.ts
> +        CoreManager.getEventuallyQueue().poll(ms);
perfect, github didnt update fast enough for me to see your comment. thanks for the help!

2024-04-14 01:48 UTC, dplewis approved these changes

2024-04-14 01:49 UTC, dplewis commented
@mtrezza This is ready for review

2024-04-15 02:12 UTC, dplewis requested changes

2024-04-15 02:12 UTC, dplewis commented on src/Parse.ts
> +  set EventuallyQueue(queue: EventuallyQueue) {
@mortenmo Can you add a unit test for this? `npm run test` you should see code coverage drop as this setter/getter isn't tested.

2024-04-22 20:51 UTC, mtrezza commented
Does the PR title make sense?

2024-04-22 23:15 UTC, mtrezza requested changes
CI fails

2024-04-23 18:32 UTC, mtrezza approved these changes
Looks good, is this ready for merge?

2024-04-23 19:34 UTC, mortenmo commented
Yeah I believe so

2024-04-24 19:10 UTC, dplewis approved these changes

2024-04-25 13:24 UTC, merged

2024-04-25 13:26 UTC, parseplatformorg commented
🎉 This change has been released in version [5.1.0-alpha.6](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-alpha.6)

2024-05-16 12:27 UTC, parseplatformorg commented
🎉 This change has been released in version [5.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-beta.1)

2024-05-16 13:23 UTC, parseplatformorg commented
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0)